# -*- coding: utf-8 -*-
"""Copy of 管网监测点管段信息匹配及碳排计算

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpLEuJ_9QbGzICtzCE3cEp3avb1zl-Hp
"""

!pip install -q geopandas shapely pyproj openpyxl
print("依赖安装完成。若后续 import 报错，请依次：菜单 Runtime → Restart runtime")

"""管线信息整理"""

# ====== 按行政区 × 管线长度区间 统计（CSV 分块版，仅长表TXT）======
import pandas as pd
import numpy as np
import os

# -------- 1) 参数区 --------
input_path  = "/content/drive/MyDrive/管网计算/管网坐标csv.csv"
length_col  = "长度(m)"     # 长度列名
district_col= "行政区"      # 行政区列名
output_dir  = "/content/drive/MyDrive/管网计算"  # 输出目录

# 长度分段（左闭右开）
bins   = [0, 1, 10, 50, 100, np.inf]
labels = ["0-1", "1-10", "10-50", "50-100", ">100"]

chunksize = 2_000_000  # 分块大小

# -------- 2) 分块统计 --------
total_agg = None

def process_chunk(chunk):
    global total_agg
    chunk.columns = chunk.columns.astype(str).str.strip()
    df = chunk[[district_col, length_col]].copy()

    # 清洗与类型
    df = df.dropna(subset=[district_col, length_col])
    df[length_col] = pd.to_numeric(df[length_col], errors="coerce")
    df = df.dropna(subset=[length_col])

    # 分段
    df["长度区间"] = pd.cut(
        df[length_col], bins=bins, labels=labels,
        right=False, include_lowest=True
    )

    # 本块分组聚合
    agg = (
        df.groupby([district_col, "长度区间"], observed=True)
          .size().rename("管线数量").reset_index()
    )

    # 累加
    if total_agg is None:
        total_agg = agg
    else:
        total_agg = pd.concat([total_agg, agg], ignore_index=True)
        total_agg = (
            total_agg.groupby([district_col, "长度区间"], observed=True)["管线数量"]
                     .sum().reset_index()
        )

# -------- 3) 分块读取并处理 --------
read_cols = [district_col, length_col]
for chunk in pd.read_csv(
    input_path,
    chunksize=chunksize,
    dtype=str,
    low_memory=True,
    usecols=read_cols,
    encoding_errors="ignore"
):
    process_chunk(chunk)

# -------- 4) 导出仅长表 --------
if total_agg is None or total_agg.empty:
    raise ValueError("未解析到有效记录，请检查列名/空值/数据格式。")

# 可选：按行政区 & 长度区间顺序排序
total_agg["长度区间"] = pd.Categorical(total_agg["长度区间"], categories=labels, ordered=True)
total_agg = total_agg.sort_values([district_col, "长度区间"]).reset_index(drop=True)

os.makedirs(output_dir, exist_ok=True)
long_txt_path  = os.path.join(output_dir, "管线长度统计_长表.txt")
total_agg.to_csv(long_txt_path, sep="\t", index=False, encoding="utf-8-sig")

print("完成✅ 已保存：", long_txt_path)
print("\n预览（长表前10行）：")
print(total_agg.head(10))

# ====== CSV 流式筛选：保留 长度(m) >= 10 的行，输出新的 CSV ======
import pandas as pd

# -------- 参数区 --------
input_csv   = "/content/drive/MyDrive/管网计算/管网坐标csv.csv"
output_csv  = "/content/drive/MyDrive/管网计算/管网坐标_长度至少10.csv"
length_col  = "长度(m)"     # 长度列名
chunksize   = 5_000_000    # 分块大小
encoding_in = "utf-8"      # 你的原文件编码，若乱码可改 "gbk"
encoding_out= "utf-8-sig"  # 输出编码（utf-8-sig 方便Excel识别中文）

# -------- 分块读取 + 过滤 --------
wrote_header = False
for chunk in pd.read_csv(
    input_csv,
    dtype=str,
    chunksize=chunksize,
    low_memory=True,
    encoding=encoding_in
):
    chunk.columns = chunk.columns.astype(str).str.strip()
    if length_col not in chunk.columns:
        raise ValueError(f"CSV中未找到列：{length_col}")

    # 转为数值（去掉千分位逗号和空格），无法转的设为 NaN
    vals = pd.to_numeric(
        chunk[length_col].astype(str).str.replace(",", "", regex=False).str.strip(),
        errors="coerce"
    )

    # 保留长度 ≥ 10 的行
    keep = vals >= 10
    out = chunk[keep]

    # 追加写出
    out.to_csv(
        output_csv,
        index=False,
        mode="a",
        header=(not wrote_header),
        encoding=encoding_out
    )
    wrote_header = True

print("✅ 筛选完成，已保存到：", output_csv)

# ========= 监测点 × 管段（自动全覆盖）：半径内多配对 + 最近点补配（已修复 KeyError） =========
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, LineString
import ast, os

# ===== 1) 参数 =====
monitor_csv = "/content/drive/MyDrive/管网计算/监测点查询列表.csv"
pipe_csv    = "/content/drive/MyDrive/管网计算/管网坐标_长度至少10.csv"

MON_ID, MON_X, MON_Y = "监测点编号", "X", "Y"
PIPE_ID, PIPE_COORDS, PIPE_START, PIPE_END = "管线编号", "投影坐标", "起点坐标", "终点坐标"

IS_LATLON, SRC_EPSG, TARGET_METER_EPSG = False, None, 3857
TOLERANCE_METERS = 50

encoding_in, encoding_out, chunksize = "utf-8", "utf-8-sig", 1_000_000
output_csv = "/content/drive/MyDrive/管网计算/监测点-管段_匹配_全覆盖.csv"

prefix_mon, prefix_pipe = "监测点_", "管段_"

# ===== 2) 工具函数 =====
def parse_xy(obj):
    if pd.isna(obj): return None
    if isinstance(obj, (list, tuple)):
        if len(obj) == 2 and all(isinstance(v, (int, float)) for v in obj): return [tuple(obj)]
        try: return [tuple(t) for t in obj]
        except: return None
    try:
        val = ast.literal_eval(str(obj))
        if isinstance(val, (list, tuple)):
            if len(val) == 2 and all(isinstance(v,(int,float)) for v in val): return [tuple(val)]
            return [tuple(t) for t in val]
    except: return None
    return None

def build_pipe_geometry(df):
    geoms, rows = [], []
    for idx, r in df.iterrows():
        coords = None
        if PIPE_COORDS in df.columns and pd.notna(r.get(PIPE_COORDS, None)):
            coords = parse_xy(r[PIPE_COORDS])
        if (not coords) and (PIPE_START in df.columns) and (PIPE_END in df.columns):
            s = parse_xy(r[PIPE_START]); e = parse_xy(r[PIPE_END])
            if s and e: coords = [s[0], e[0]]
        if coords and len(coords) >= 2:
            try:
                geoms.append(LineString(coords)); rows.append(idx)
            except: pass
    if not rows: return gpd.GeoDataFrame(df.iloc[0:0].copy(), geometry=[])
    sub = df.loc[rows].copy()
    return gpd.GeoDataFrame(sub, geometry=geoms, crs=None)

def _dedup_cols(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    if gdf.columns.duplicated().any():
        gdf = gdf.loc[:, ~gdf.columns.duplicated()].copy()
    return gdf

# ===== 3) 监测点：读入->建点->CRS =====
mon = pd.read_csv(monitor_csv, dtype=str, low_memory=True, encoding=encoding_in)
mon.columns = mon.columns.astype(str).str.strip()
for c in (MON_X, MON_Y):
    if c not in mon.columns: raise ValueError(f"监测点CSV缺少列：{c}")
    mon[c] = pd.to_numeric(mon[c].astype(str).str.replace(",", "", regex=False).str.strip(), errors="coerce")
mon_valid = mon.dropna(subset=[MON_X, MON_Y]).copy()

gdf_mon = gpd.GeoDataFrame(mon_valid, geometry=[Point(xy) for xy in zip(mon_valid[MON_X], mon_valid[MON_Y])], crs=None)
# CRS 加固
if IS_LATLON:
    gdf_mon.set_crs(4326, inplace=True, allow_override=True)
    gdf_mon = gdf_mon.to_crs(TARGET_METER_EPSG)
elif SRC_EPSG is not None:
    gdf_mon.set_crs(SRC_EPSG, inplace=True, allow_override=True)
else:
    gdf_mon.set_crs(TARGET_METER_EPSG, inplace=True, allow_override=True)

# 半径缓冲（多配对候选）
gdf_mon_buf = gdf_mon.copy()
gdf_mon_buf["geometry"] = gdf_mon_buf.geometry.buffer(TOLERANCE_METERS)

# 监测点前缀映射（不含 geometry）
mon_cols_raw = [c for c in gdf_mon.columns if c != "geometry"]
mon_cols_prefixed = {c: f"{prefix_mon}{c}" for c in mon_cols_raw}

# ===== 4) 输出准备 =====
if os.path.exists(output_csv): os.remove(output_csv)
wrote_header = False
print("监测点数量：", len(gdf_mon))
print("开始分块处理管段 CSV ...")

pipe_cols_prefixed = None

# ===== 5) 分块处理管段 =====
for i, chunk in enumerate(pd.read_csv(pipe_csv, dtype=str, chunksize=chunksize, low_memory=True, encoding=encoding_in), start=1):
    chunk.columns = chunk.columns.astype(str).str.strip()
    pipe_df_raw = chunk.copy()

    gdf_pipe = build_pipe_geometry(pipe_df_raw)
    if gdf_pipe.empty:
        print(f"[块 {i}] 没有有效管段几何，跳过。"); continue

    # CRS 对齐
    if gdf_pipe.crs is None:
        gdf_pipe.set_crs(gdf_mon.crs, inplace=True, allow_override=True)
    elif gdf_pipe.crs != gdf_mon.crs:
        gdf_pipe = gdf_pipe.to_crs(gdf_mon.crs)

    # 记录本块所有管段ID（用于补配去重）
    all_pipe_ids = set(gdf_pipe[PIPE_ID].dropna().astype(str))

    # === A) 半径内多对多匹配 ===
    left  = _dedup_cols(gdf_mon_buf.copy())
    right = _dedup_cols(gdf_pipe.copy())

    # sjoin 前加前缀（非几何列）
    left_pref  = left.rename(columns={c: mon_cols_prefixed.get(c, c) for c in mon_cols_raw})
    if pipe_cols_prefixed is None:
        pipe_cols_raw = [c for c in gdf_pipe.columns if c != "geometry"]
        pipe_cols_prefixed = {c: f"{prefix_pipe}{c}" for c in pipe_cols_raw}
    right_pref = right.rename(columns={c: pipe_cols_prefixed.get(c, c) for c in right.columns if c != "geometry"})

    joined = gpd.sjoin(left_pref, right_pref, how="inner", predicate="intersects")
    if not joined.empty:
        joined = joined.reset_index(drop=False).rename(columns={"index": "mon_index"})
        point_geom = gdf_mon.geometry.iloc[joined["mon_index"]].reset_index(drop=True)
        joined = joined.drop(columns=["geometry"]); joined["geometry"] = point_geom
        gdf_joined = gpd.GeoDataFrame(joined, geometry="geometry", crs=gdf_mon.crs)
        geom_line_col = "geometry_right" if "geometry_right" in gdf_joined.columns else "geometry"
        gdf_joined["距离_米"] = gdf_joined.geometry.distance(gdf_joined[geom_line_col])
        gdf_joined = gdf_joined[gdf_joined["距离_米"] <= TOLERANCE_METERS]
    else:
        gdf_joined = gpd.GeoDataFrame(joined, geometry=[], crs=gdf_mon.crs)

    covered_pipe_ids = set()
    if not gdf_joined.empty and f"{prefix_pipe}{PIPE_ID}" in gdf_joined.columns:
        covered_pipe_ids = set(gdf_joined[f"{prefix_pipe}{PIPE_ID}"].dropna().astype(str))

    # === B) 最近点补配（修复 KeyError：仅取 nearest 里实际存在的列） ===
    need_fill = [idx for idx, r in gdf_pipe[[PIPE_ID]].dropna().iterrows()
                 if str(r[PIPE_ID]) not in covered_pipe_ids]

    if need_fill:
        gdf_pipe_need = gdf_pipe.loc[need_fill].copy()
        nearest = gpd.sjoin_nearest(gdf_pipe_need, gdf_mon, how="left", distance_col="距离_米")

        # 右侧（管段）：nearest 中实际存在的列
        pipe_cols_raw = [c for c in gdf_pipe.columns if c != "geometry"]
        pipe_cols_in_nearest = [c for c in pipe_cols_raw if c in nearest.columns]
        # 左侧（监测点）：nearest 中实际存在的列
        mon_cols_in_nearest = [c for c in mon_cols_raw if c in nearest.columns]

        if pipe_cols_prefixed is None:
            pipe_cols_prefixed = {c: f"{prefix_pipe}{c}" for c in pipe_cols_raw}

        nearest_pipe = nearest[pipe_cols_in_nearest].rename(
            columns={c: pipe_cols_prefixed.get(c, c) for c in pipe_cols_in_nearest}
        )
        nearest_mon = nearest[mon_cols_in_nearest].rename(
            columns={c: mon_cols_prefixed.get(c, c) for c in mon_cols_in_nearest}
        )

        fill_df = pd.concat(
            [nearest_mon.reset_index(drop=True),
             nearest_pipe.reset_index(drop=True),
             nearest[["距离_米"]].reset_index(drop=True)],
            axis=1
        )
        fill_df = fill_df.loc[:, ~fill_df.columns.duplicated()]
        fill_df["match_type"] = "nearest_fill"
    else:
        fill_df = pd.DataFrame(columns=[])

    # === 汇总写出 ===
    out_blocks = []
    if not gdf_joined.empty:
        mon_pref_cols  = [mon_cols_prefixed[c] for c in mon_cols_raw if mon_cols_prefixed.get(c) in gdf_joined.columns]
        pipe_pref_cols = [v for v in pipe_cols_prefixed.values() if v in gdf_joined.columns]
        blockA = pd.concat(
            [gdf_joined[mon_pref_cols].reset_index(drop=True),
             gdf_joined[pipe_pref_cols].reset_index(drop=True),
             gdf_joined[["距离_米"]].reset_index(drop=True)],
            axis=1
        )
        blockA["match_type"] = "within_radius"
        out_blocks.append(blockA)

    if not fill_df.empty:
        out_blocks.append(fill_df)

    if out_blocks:
        out_df = pd.concat(out_blocks, axis=0, ignore_index=True)
        out_df.to_csv(output_csv, index=False, mode="a", header=(not wrote_header), encoding=encoding_out)
        wrote_header = True
        print(f"[块 {i}] 写出 {len(out_df)} 行（半径内{len(out_blocks[0]) if out_blocks else 0} + 补配{(len(out_blocks[1]) if len(out_blocks)>1 else 0)}）")
    else:
        print(f"[块 {i}] 无匹配结果（此块为空）。")

print("✅ 完成：", output_csv)

"""压力监测点按区级整理"""

# -*- coding: utf-8 -*-
import pandas as pd, os

# ========= 路径 =========
base_path = r"/content/drive/MyDrive/管网计算/管网压力流量区域匹配/"
pressure_file = os.path.join(base_path, "压力监测点数据.xls")

# =========（可选）限制输出区域；留空或注释则保留全部检测到的区域 =========
zone_pressure_map = {
    "东涌": [],
    "黄阁": [],
    "南沙": [],
    "横沥": [],
    "万顷沙": [],
    "大岗": [],
    "龙穴岛": [],
}
# 若想保留所有检测到的区域，请把 keep_zone_map 设为 None
# keep_zone_map = None
keep_zone_map = zone_pressure_map

# ========= 读取（两行表头：第1行=站点，第2行=区域）并聚合到“区级·按小时·中位数” =========
def read_zone_pressure_v2(pressure_path, keep_zone_map=None):
    xl = pd.ExcelFile(pressure_path)
    frames, diags = [], []

    for sh in xl.sheet_names:
        df0 = xl.parse(sh, header=None)
        if df0.empty or df0.shape[1] < 2:
            continue

        # === 新逻辑：第1行=区域，第2行=站点 ===
        zone_row_idx = 0
        site_row_idx = 1

        # 找时间列所在行（第3行）
        data_start_row = 2
        time_col = df0.iloc[data_start_row, 0]

        # 解析区域 & 站点
        zone_row = df0.iloc[zone_row_idx].astype(str).replace({"nan":None}).ffill()
        site_row = df0.iloc[site_row_idx].astype(str)

        # 构造列名
        cols = ["time"]
        for j in range(1, df0.shape[1]):
            z = str(zone_row.iloc[j]).strip()
            s = str(site_row.iloc[j]).strip()
            cols.append(f"{z}|{s}")

        data = df0.iloc[data_start_row:].copy()
        data.columns = cols

        # 解析时间
        data["time"] = pd.to_datetime(data["time"], errors="coerce")
        data = data.dropna(subset=["time"])
        data["hour"] = data["time"].dt.floor("h")
        data = data.drop(columns=["time"])

        # 转数字
        value_cols = [c for c in data.columns if c != "hour"]
        for c in value_cols:
            data[c] = pd.to_numeric(data[c], errors="coerce")

        # 宽 → 长
        long = []
        for c in value_cols:
            if "|" in c:
                z, s = c.split("|", 1)
            else:
                z = c
            long.append(data[["hour", c]].rename(columns={c: "value"}).assign(zone=z))
        long_df = pd.concat(long, ignore_index=True)

        # 按“小时×区域”中位数
        zone_hour = (
            long_df.groupby(["hour","zone"])["value"]
            .median()
            .reset_index()
            .pivot(index="hour", columns="zone", values="value")
        )

        frames.append(zone_hour)
        diags.append({
            "sheet": sh,
            "mode": "zone-row-1-site-row-2",
            "zones_found": ",".join(map(str, zone_hour.columns)),
            "rows_hour": len(zone_hour)
        })

    if not frames:
        return pd.DataFrame(columns=["hour"]), pd.DataFrame(diags)

    p = pd.concat(frames).groupby(level=0).median().reset_index()

    if isinstance(keep_zone_map, dict):
        wanted = ["hour"] + [z for z in keep_zone_map if z in p.columns]
        p = p[wanted]

    return p, pd.DataFrame(diags)

# ========== 主流程 ==========
zone_pressure, diag = read_zone_pressure_v2(pressure_file, keep_zone_map=keep_zone_map)

# 导出
out_csv = os.path.join(base_path, "区级压力_小时.csv")
zone_pressure.to_csv(out_csv, index=False, encoding="utf-8-sig")

diag_csv = os.path.join(base_path, "区级压力_诊断.csv")
diag.to_csv(diag_csv, index=False, encoding="utf-8-sig")

print("🎉 输出：", out_csv)
print("🧪 诊断：", diag_csv)
print("📈 区域列：", [c for c in zone_pressure.columns if c != "hour"])
print("📦 行数(小时数)：", len(zone_pressure))

"""流量数据匹配及碳排计算"""

# -*- coding: utf-8 -*-
import pandas as pd, numpy as np, os, glob, re

# ================== 路径 ==================
BASE = "/content/drive/MyDrive/管网计算/管网压力流量区域匹配/"

PRESSURE_POINT_FILE = "/content/drive/MyDrive/管网计算/管网压力流量区域匹配/压力监测点数据.xls"
MONITOR_PIPE_CSV    = "/content/drive/MyDrive/管网计算/管网监测点信息匹配/监测点-管段_匹配_全覆盖.csv"
FLOW_DIR            = os.path.join(BASE, "流量监测点数据")

OUT_XLSX = os.path.join(BASE, "管网碳排结果_按压力监测点_坐标匹配.xlsx")

# ================== 常数 ==================
EF = 0.5271
ETA_PUMP, ETA_MOTOR, ETA_VFD = 0.75, 0.96, 0.98
ETA_TOTAL = ETA_PUMP * ETA_MOTOR * ETA_VFD
RHO, G = 1000.0, 9.81
WEEK_START = "MON"

# ================== 压力监测点 → 区标签 ==================
PRESS_POINT_ZONE = {
    # 东涌
    "新联一桥": "东涌",
    "东导小桥": "东涌",
    "大网顶中桥": "东涌",
    "石基善教旧桥": "东涌",
    "鱼窝头大道东心小桥": "东涌",
    "港科大(hd)": "东涌",
    "万洲中桥": "东涌",
    "大简中桥": "东涌",
    # 黄阁
    "黄阁水厂hd": "黄阁",
    "小虎南二路14号": "黄阁",
    "黄阁镇hd": "黄阁",
    "沙仔汽车码头": "黄阁",
    # 南沙
    "南沙牌坊hd": "南沙",
    "老明记": "南沙",
    "南沙客运港hd": "南沙",
    "滨海公园": "南沙",
    "名幸门口边": "南沙",
    "建滔进水hd": "南沙",
    "南沙旧镇": "南沙",
    "凫洲大桥泵房": "南沙",
    # 横沥
    "IFF会展中心(hd)": "横沥",
    "中交汇通中心(hd)": "横沥",
    # 万顷沙
    "万地雅涛阁hd": "万顷沙",
    "新垦社区hd": "万顷沙",
    "灵新十七涌hd": "万顷沙",
    "灵新路十九涌hd": "万顷沙",
    "民兴桥hd": "万顷沙",
    "万环西路十五涌": "万顷沙",
}

# ================== 小工具 ==================
def normalize_cols(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def pick_time_col(df):
    cols = df.columns
    cand = [c for c in cols if any(k in c for k in
           ["采集时间","时间","时刻","Time","time","DATE","Date","date","Datetime","datetime"])]
    return cand[0] if cand else None

def pick_flow_col(df):
    keys = ["数值", "瞬时流量", "流量", "流量(m³/h)", "流量(m3/h)", "当前流量"]
    for k in keys:
        for c in df.columns:
            if k in c and pd.api.types.is_numeric_dtype(df[c]):
                return c
    numeric = [c for c in df.select_dtypes(include=["float","int"]).columns]
    bad = [c for c in numeric if any(k in c for k in ["编码","编号","序号","ID","id"])]
    good = [c for c in numeric if c not in bad]
    return good[0] if good else (numeric[0] if numeric else None)

def normalize_point_name(s: str) -> str:
    """统一监测点名称：去掉路径、扩展名、末尾流水号等"""
    s = str(s).strip()
    base = os.path.basename(s)
    base = os.path.splitext(base)[0]
    base = re.sub(r"_\d+$", "", base)   # 去掉 _1751875...
    for t in ["超声波"]:
        base = base.replace(t, "")
    return base.strip()

def clean_name_from_filename(fname):
    return normalize_point_name(fname)

# ======================================================
# 1) 先读流量时序，得到“有数据的流量监测点”集合
# ======================================================
xlsx_list = glob.glob(os.path.join(FLOW_DIR, "*.xlsx"))
if not xlsx_list:
    raise FileNotFoundError(f"未在文件夹找到xlsx：{FLOW_DIR}")

flow_rows = []
for f in xlsx_list:
    df = pd.read_excel(f)
    df = normalize_cols(df)
    tcol = pick_time_col(df)
    fcol = pick_flow_col(df)
    if not tcol or not fcol:
        print(f"⚠️ 跳过（未识别时间/流量列）：{os.path.basename(f)} | time={tcol} | flow={fcol}")
        continue

    tmp = df[[tcol, fcol]].copy()
    tmp.columns = ["time","flow"]
    tmp["time"] = pd.to_datetime(tmp["time"], errors="coerce")
    tmp = tmp.dropna(subset=["time"])
    tmp["hour"] = tmp["time"].dt.floor("H")

    flow_point = clean_name_from_filename(f)
    grp = tmp.groupby("hour", as_index=False)["flow"].sum()
    grp["flow_point"] = flow_point
    flow_rows.append(grp)

if not flow_rows:
    raise RuntimeError("未成功解析任何流量文件。")

flow_all = pd.concat(flow_rows, ignore_index=True)
flow_hourly = (flow_all.groupby(["hour","flow_point"], as_index=False)["flow"]
               .sum()
               .rename(columns={"flow":"flow_m3_h"}))

print("✅ 流量监测点小时数据行数：", len(flow_hourly))
print("✅ 有时序数据的流量监测点：", flow_hourly["flow_point"].unique())

FLOW_POINTS_WITH_TS = set(flow_hourly["flow_point"].unique())
FLOW_START = flow_hourly["hour"].min()
FLOW_END   = flow_hourly["hour"].max()
print("✅ 流量数据时间范围：", FLOW_START, " ~ ", FLOW_END)

# ======================================================
# 2) 匹配表里提取坐标（只保留有时序的流量点）
# ======================================================
m = pd.read_csv(MONITOR_PIPE_CSV, encoding="utf-8", low_memory=False)
m = normalize_cols(m)
cols = m.columns

name_col = next(c for c in cols if ("监测点_监测点名称" in c) or ("监测点名称" in c))
x_col    = next(c for c in cols if ("监测点_X" in c) or ("X" in c and "监测点" in c))
y_col    = next(c for c in cols if ("监测点_Y" in c) or ("Y" in c and "监测点" in c))
type_col = None
for c in cols:
    if "类型" in c:
        type_col = c
        break

print("监测点名称列:", name_col, "  坐标X列:", x_col, "  坐标Y列:", y_col, "  类型列:", type_col)

sub = m[[name_col, x_col, y_col] + ([type_col] if type_col else [])].dropna(subset=[name_col, x_col, y_col])
sub[name_col] = sub[name_col].astype(str).str.strip()
sub["name_norm"] = sub[name_col].apply(normalize_point_name)

# 类型区分
if type_col:
    sub[type_col] = sub[type_col].astype(str)
    press_mask = sub[type_col].str.contains("压")
    flow_mask  = sub[type_col].str.contains("流")
else:
    pressure_names_norm = {normalize_point_name(n) for n in PRESS_POINT_ZONE.keys()}
    press_mask = sub["name_norm"].isin(pressure_names_norm)
    flow_mask  = ~sub["name_norm"].isin(pressure_names_norm)

press_sub = sub[press_mask].copy()
flow_sub  = sub[flow_mask].copy()

# 只保留“有时序数据”的流量点
flow_sub = flow_sub[flow_sub["name_norm"].isin(FLOW_POINTS_WITH_TS)]

press_coords = (press_sub
                .groupby("name_norm", as_index=False)
                .agg({x_col:"mean", y_col:"mean"}))
flow_coords = (flow_sub
               .groupby("name_norm", as_index=False)
               .agg({x_col:"mean", y_col:"mean"}))

press_coord_dict = {row["name_norm"]: (row[x_col], row[y_col])
                    for _, row in press_coords.iterrows()}
flow_coord_dict  = {row["name_norm"]: (row[x_col], row[y_col])
                    for _, row in flow_coords.iterrows()}

print(f"✅ 有坐标的压力监测点个数：{len(press_coord_dict)}")
print(f"✅ 既有坐标又有时序数据的流量监测点个数：{len(flow_coord_dict)}")

# 最近邻映射：压力 → 流量
PRESS_TO_FLOW_MAP = {}
for pname, (px, py) in press_coord_dict.items():
    best_f = None
    best_d2 = None
    for fname, (fx, fy) in flow_coord_dict.items():
        d2 = (px - fx)**2 + (py - fy)**2
        if best_d2 is None or d2 < best_d2:
            best_d2 = d2
            best_f = fname
    PRESS_TO_FLOW_MAP[pname] = best_f

print("✅ 压力监测点 ↔ 最近流量监测点 映射（前 10 个）：")
for i, (k, v) in enumerate(PRESS_TO_FLOW_MAP.items()):
    print("   ", k, "→", v)
    if i >= 9:
        break

# ======================================================
# 3) 压力监测点时序（并切到流量数据时间范围内）
# ======================================================
if PRESSURE_POINT_FILE.lower().endswith((".xls", ".xlsx")):
    p_raw = pd.read_excel(PRESSURE_POINT_FILE, header=1)
else:
    p_raw = pd.read_csv(PRESSURE_POINT_FILE, encoding="utf-8", low_memory=False)

p_raw = normalize_cols(p_raw)
tcol_p = pick_time_col(p_raw) or p_raw.columns[0]

p_raw[tcol_p] = pd.to_datetime(p_raw[tcol_p], errors="coerce")
p_raw = p_raw.dropna(subset=[tcol_p]).copy()
p_raw["hour"] = p_raw[tcol_p].dt.floor("H")

# 关键：只保留与流量数据重叠的时间段，避免前几个月全是 0
p_raw = p_raw[(p_raw["hour"] >= FLOW_START) & (p_raw["hour"] <= FLOW_END)]

zone_headers = {"东涌","黄阁","南沙","横沥","万顷沙","龙穴岛"}
value_cols = []
for c in p_raw.columns:
    if c in [tcol_p, "hour"]:
        continue
    if str(c).startswith("Unnamed"):
        continue
    if c in zone_headers:
        continue
    value_cols.append(c)

print("✅ 在压力监测点数据中识别到监测点列数：", len(value_cols))
print("   示例：", value_cols[:10])

p_rows = []
for c in value_cols:
    pt_name = str(c).strip()
    tmp = p_raw[["hour", c]].copy()
    tmp.columns = ["hour","pressure_m"]
    tmp["point"] = pt_name
    p_rows.append(tmp)

press_long = pd.concat(p_rows, ignore_index=True)
press_hourly = (press_long
                .dropna(subset=["pressure_m"])
                .groupby(["hour","point"], as_index=False)["pressure_m"]
                .mean())

press_hourly["zone"] = press_hourly["point"].map(PRESS_POINT_ZONE)
press_hourly["point_norm"] = press_hourly["point"].apply(normalize_point_name)

# 映射最近的流量点名（规范后）
press_hourly["flow_point"] = press_hourly["point_norm"].map(PRESS_TO_FLOW_MAP)

# ======================================================
# 4) 合并流量 + “按小时按流量点平均分摊”避免多算
# ======================================================
hourly = pd.merge(
    press_hourly,
    flow_hourly,
    left_on=["hour","flow_point"],
    right_on=["hour","flow_point"],
    how="left"
)

hourly["flow_m3_h"] = pd.to_numeric(hourly["flow_m3_h"], errors="coerce").fillna(0.0)
hourly["pressure_m"] = pd.to_numeric(hourly["pressure_m"], errors="coerce")

# ——关键：按每个小时、每个流量点统计有多少个压力点在用——
hourly["n_share"] = hourly.groupby(["hour","flow_point"])["point"].transform("nunique")
hourly["n_share"] = hourly["n_share"].replace(0, 1)

# 保留原始流量做 sanity check
hourly["flow_m3_h_orig"] = hourly["flow_m3_h"]

# 把这一小时的流量在对应压力点之间均分，避免总量被放大
hourly["flow_m3_h"] = hourly["flow_m3_h"] / hourly["n_share"]

hourly = hourly.rename(columns={"hour":"ts"})
hourly["ts"] = pd.to_datetime(hourly["ts"], errors="coerce")
hourly = hourly.dropna(subset=["ts"])

print("✅ 检查：原始流量总和 vs 分摊后总和（应该非常接近）")
print("   原始：", hourly["flow_m3_h_orig"].sum(), "  分摊后：", hourly["flow_m3_h"].sum())

# ======================================================
# 5) 计算能耗与碳排
# ======================================================
hourly["Q_m3s"]     = hourly["flow_m3_h"] / 3600.0
hourly["P_hyd_W"]   = RHO * G * hourly["Q_m3s"] * hourly["pressure_m"]
hourly["P_elec_kW"] = (hourly["P_hyd_W"] / max(ETA_TOTAL, 1e-6)) / 1000.0
hourly["kWh"]       = hourly["P_elec_kW"]
hourly["CO2e_kg"]   = hourly["kWh"] * EF
hourly["SE_kWh_m3"] = np.where(hourly["flow_m3_h"]>0, hourly["kWh"]/hourly["flow_m3_h"], np.nan)
hourly["I_kg_m3"]   = np.where(hourly["flow_m3_h"]>0, hourly["CO2e_kg"]/hourly["flow_m3_h"], np.nan)

hourly["day"]   = hourly["ts"].dt.floor("D")
hourly["week"]  = hourly["ts"].dt.to_period(f"W-{WEEK_START}").dt.start_time
hourly["month"] = hourly["ts"].dt.to_period("M").dt.start_time
hourly["year"]  = hourly["ts"].dt.to_period("Y").dt.start_time

def rollup(df_in, key):
    g = (df_in.groupby([key,"zone","point"], as_index=False)
               .agg({
                    "kWh":"sum",
                    "CO2e_kg":"sum",
                    "flow_m3_h":"sum",
                    "pressure_m":"mean"
               }))
    g["SE_kWh_m3"] = np.where(g["flow_m3_h"]>0, g["kWh"]/g["flow_m3_h"], np.nan)
    g["I_kg_m3"]   = np.where(g["flow_m3_h"]>0, g["CO2e_kg"]/g["flow_m3_h"], np.nan)
    return g.rename(columns={key:"period"})

daily   = rollup(hourly, "day")
weekly  = rollup(hourly, "week")
monthly = rollup(hourly, "month")
yearly  = rollup(hourly, "year")

# ======================================================
# 6) 导出
# ======================================================
with pd.ExcelWriter(OUT_XLSX, engine="openpyxl") as xw:
    hourly.to_excel(xw,  "Hourly_PressurePoint", index=False)
    daily.to_excel(xw,   "Daily_PressurePoint", index=False)
    weekly.to_excel(xw,  "Weekly_PressurePoint", index=False)
    monthly.to_excel(xw, "Monthly_PressurePoint", index=False)
    yearly.to_excel(xw,  "Yearly_PressurePoint", index=False)

print("🎉 完成：按压力监测点计算碳排（避免重复计算），文件：", OUT_XLSX)